//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Views._3D {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bishop_Mesh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bishop_Mesh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Views._3D.Bishop_Mesh", typeof(Bishop_Mesh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.29276333,0.28394628,0.9130521 0.70710678,0.70710678,0 0.55557069,0.8314693,0 0.23140666,0.34632449,0.90912612 0.0074833426,0.018066304,-0.99980879 0.38268493,0.92387891,0 0.55557069,0.8314693,0 0.010864101,0.016259257,-0.99980879 0.0038149908,0.019179104,-0.99980879 0.19509179,0.98078499,0 5.6327789E-08,0.01955484,-0.99980879 2.8805037E-06,1,0 -0.0038149349,0.019179106,-0.99980879
        ///-0.19508902,0.98078554,0 -0.0074832733,0.018066329,-0.99980879 -0.38268145,0.92388035,0 -0.010864068,0.016259264,-0.99980879  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Normals {
            get {
                return ResourceManager.GetString("Normals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.5999999,-6.4000001,0.1 3.5999999,-6.4000001,0.088361003 3.4714179,-6.294476,0.088361003 3.4714179,-6.294476,0.1 3.324719,-6.216063,0 3.324719,-6.216063,0.016596001 3.4714179,-6.294476,0.016596001 3.4714179,-6.294476,0 3.1655409,-6.1677771,0 3.1655409,-6.1677771,0.016596001 3.000001,-6.1514721,0 3.000001,-6.1514721,0.016596001 2.8344619,-6.1677761,0
        ///2.8344619,-6.1677761,0.016596001 2.675283,-6.2160621,0 2.675283,-6.2160621,0.016596001 2.528584,-6.2944741,0 2.528584,-6.2944741,0.016596001 2.400001,-6.39999 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.63822906,0.36177094 0.63726596,0.36273404 0.60651441,0.3364467 0.607242,0.33526493 0.56910119,0.32593684 0.56974464,0.32415827 0.60219154,0.34343711 0.60123091,0.34498357 0.5350222,0.31385907 0.53534442,0.31192429 0.5000002,0.30971252 0.5000002,0.30772227 0.46497841,0.31385885 0.4646562,0.31192408 0.43089923,0.32593661 0.43025578,0.32415805 0.39876954,0.34498315 0.39780891,0.34343668 0.3697112,0.36971076 0.36844482,0.36844438 0.34498339,0.39876912 0.34343693,0.39780849 0.32593681,0.43089901
        ///0.32415825,0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextureCoordinates {
            get {
                return ResourceManager.GetString("TextureCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 2 0 2 3 4 5 6 4 6 7 8 9 5 8 5 4 8 10 11 8 11 9 12 13 11 12 11 10 14 15 13 14 13 12 16 17 15 16 15 14 16 18 19 16 19 17 20 21 19 20 19 18 20 22 23 20 23 21 24 25 23 24 23 22 26 27 25 26 25 24 28 29 27 28 27 26 28 30 31 28 31 29 32 33 31 32 31 30 32 34 35 32 35 33 36 37 35 36 35 34 36 38 39 36 39 37 40 41 39 40 39 38 40 42 43 40 43 41 44 45 43 44 43 42 46 47 45 46 45 44 48 49 47 48 47 46 48 50 51 48 51 49 50 52 53 50 53 51 54 55 53 54 53 52 54 56 57 54 57 55 58 59 57 58 57 56 58 60 61 58 61 59 62 63 61 62 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriangleIndices {
            get {
                return ResourceManager.GetString("TriangleIndices", resourceCulture);
            }
        }
    }
}
