//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Views._3D {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChessBoard_Mesh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChessBoard_Mesh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Views._3D.ChessBoard_Mesh", typeof(ChessBoard_Mesh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -6,6,0 -6,7.999999,0 -8.000001,8,0 -8,6,0 -8,3.999999,0 -8,1.999999,0 -6,2,0 -6,3.999999,0 -8,-1E-06,0 -8,-2.000001,0 -6,-2,0 -6,-1E-06,0 -8,-4,0
        ///-8,-6,0 -6,-6,0 -5.999999,-4.000001,0 -4,4,0 -4,5.999999,0 -4,0,0 -4,1.999999,0 -4,-4,0 -3.999999,-2.000001,0 -6,-8,0 -3.999999,-8,0 -3.999999,-6.000001,0 -4,8,0
        ///-2,6,0 -2,8,0 -2,2,0 -2,3.999999,0 -2,-2,0 -2,-1E-06,0 -2,-6,0 -1.999999,-4,0 0,4,0 0,6,0 0,0,0 0,2,0 0,-4,0
        ///1E-06,-2,0 -1.999999,-8,0 1E-06,-8,0 1E-06,-6,0 -1E-06,8,0 2,6,0 2,8,0 2,2,0 2,4,0 2,-2,0 2, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.25,0.25 0.29516722,0.20483278 0.24999998,0.25000002 0.20483276,0.29516724 0.14758359,0.35241641 0.077979095,0.42202091 0.10241638,0.39758362 0.18716701,0.31283299 3.9684349E-08,0.50000004 0.077979166,0.57797917 0.10241638,0.60241638 5.2817894E-08,0.50000005 0.14758362,0.64758362 0.20483276,0.70483276 0.25,0.75 0.1871671,0.6871671 0.25,0.25 0.31283293,0.18716707 0,0.5 0.14758356,0.35241644 0.25,0.75 0.14758371,0.64758371 0.29516724,0.79516724
        ///0.35241641,0.85241641 0.31283302,0.81283302 0.35241638,0.147583 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextureCoordinates {
            get {
                return ResourceManager.GetString("TextureCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 2 0 2 3 4 5 6 4 6 7 8 9 10 8 10 11 12 13 14 12 14 15 0 7 16 0 16 17 6 11 18 6 18 19 10 15 20 10 20 21 14 22 23 14 23 24 25 17 26 25 26 27 16 19 28 16 28 29 18 21 30 18 30 31 20 24 32 20 32 33 26 29 34 26 34 35 28 31 36 28 36 37 30 33 38 30 38 39 32 40 41 32 41 42 43 35 44 43 44 45 34 37 46 34 46 47 36 39 48 36 48 49 38 42 50 38 50 51 44 47 52 44 52 53 46 49 54 46 54 55 48 51 56 48 56 57 50 58 59 50 59 60 61 53 62 61 62 63 52 55 64 52 64 65 54 57 66 54 66 67 56 60 68 56 68 69 62 65 70 62 70 71 64 67 72 6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriangleIndices {
            get {
                return ResourceManager.GetString("TriangleIndices", resourceCulture);
            }
        }
    }
}
