//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Views._3D {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class King_Mesh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal King_Mesh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Views._3D.King_Mesh", typeof(King_Mesh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.37902057,0.15045215,0.91307588 0.92370174,0.38311237,0 0.83121073,0.55595749,0 0.34616492,0.23153214,0.90915495 0.01379181,0.013804618,-0.99980959 0.70677851,0.7074349,0 0.83121073,0.55595749,0 0.016219926,0.010848741,-0.99980959 0.010833725,0.016229973,-0.99980959 0.55518768,0.8317251,0 0.0074592551,0.018031646,-0.99980959 0.38225922,0.92405513,0 0.0037980337,0.019140411,-0.99980959
        ///0.19463526,0.98087569,0 -9.0777578E-06,0.01951361,-0.99980959 -0.0004652013,0.99999989,0 -0.0038157987,0.019136892,-0.9998 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Normals {
            get {
                return ResourceManager.GetString("Normals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.783787,-6.6749182,0.1 1.783787,-6.6749182,0.088376001 1.705307,-6.5282569,0.088376001 1.705307,-6.5282569,0.1 1.599722,-6.3997231,0 1.599722,-6.3997231,0.016561 1.705307,-6.5282569,0.016561 1.705307,-6.5282569,0 1.47109,-6.2942572,0 1.47109,-6.2942572,0.016561 1.324355,-6.2159119,0 1.324355,-6.2159119,0.016561 1.165154,-6.1676989,0
        ///1.165154,-6.1676989,0.016561 0.99960703,-6.1514721,0 0.99960703,-6.1514721,0.016561 0.83407497,-6.1678529,0 0.83407497,-6.1678529,0.016561 0.67491901,-6.2162132,0 0.67491901,- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.68356154,0.42738845 0.68221846,0.42786841 0.66207596,0.39428706 0.66323908,0.39356899 0.62915715,0.3707163 0.6304033,0.36946879 0.65518214,0.39856142 0.65366125,0.39950853 0.60034754,0.34623562 0.60129321,0.34471353 0.56847957,0.32739827 0.56911303,0.32564921 0.53466834,0.31546862 0.53498527,0.31356719 0.49991767,0.31138791 0.49991692,0.30943261 0.46516914,0.31550714 0.46485071,0.31360621 0.43136472,0.32747193 0.43072977,0.32572379 0.39950835,0.34633878 0.39856124,0.34481789 0.37071609,0.3708429
        ///0.369468 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextureCoordinates {
            get {
                return ResourceManager.GetString("TextureCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 2 0 2 3 4 5 6 4 6 7 8 9 5 8 5 4 8 10 11 8 11 9 12 13 11 12 11 10 14 15 13 14 13 12 16 17 15 16 15 14 16 18 19 16 19 17 20 21 19 20 19 18 20 22 23 20 23 21 24 25 23 24 23 22 26 27 25 26 25 24 28 29 27 28 27 26 28 30 31 28 31 29 32 33 31 32 31 30 32 34 35 32 35 33 36 37 35 36 35 34 36 38 39 36 39 37 40 41 39 40 39 38 40 42 43 40 43 41 44 45 43 44 43 42 46 47 45 46 45 44 48 49 47 48 47 46 48 50 51 48 51 49 50 52 53 50 53 51 54 55 53 54 53 52 54 56 57 54 57 55 58 59 57 58 57 56 58 60 61 58 61 59 62 63 61 62 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriangleIndices {
            get {
                return ResourceManager.GetString("TriangleIndices", resourceCulture);
            }
        }
    }
}
