//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Views._3D {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Knight_Mesh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Knight_Mesh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Views._3D.Knight_Mesh", typeof(Knight_Mesh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.41116642,0.4037108,0.81728806 0.70710678,0.70710678,0 0.55557069,0.8314693,0 0.32447203,0.48560527,0.8117299 0.0080246637,0.019373148,-0.99978012 0.38268519,0.92387881,0 0.55557069,0.8314693,0 0.011649968,0.017435388,-0.99978012 0.008176536,0.041105901,-0.99912134 0.19509179,0.98078499,0 1.2072558E-07,0.041911272,-0.99912134 2.8805037E-06,1,0 -0.0040908926,0.020566449,-0.99978012
        ///-0.19508902,0.98078554,0 -0.0080245787,0.019373179,-0.99978012 -0.3826812,0.92388046,0 -0.023284527,0.034847837,-0.99912134 -0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Normals {
            get {
                return ResourceManager.GetString("Normals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.5999999,-6.4000001,0.1 5.5999999,-6.4000001,0.082318999 5.4714179,-6.294476,0.082318999 5.4714179,-6.294476,0.1 5.324719,-6.216063,0 5.324719,-6.216063,0.017797001 5.4714179,-6.294476,0.017797001 5.4714179,-6.294476,0 5.1655412,-6.1677771,0 5.1655412,-6.1677771,0.017797001 5.000001,-6.1514721,0 5.000001,-6.1514721,0.017797001 4.8344622,-6.1677761,0
        ///4.8344622,-6.1677761,0.017797001 4.675283,-6.2160621,0 4.675283,-6.2160621,0.017797001 4.528584,-6.2944741,0 4.528584,-6.2944741,0.017797001 4.400001,-6.39999 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.63363037,0.36636963 0.63224749,0.36775251 0.60271624,0.34259139 0.603764,0.34090034 0.56696941,0.33179244 0.56762648,0.3299935 0.59903121,0.34851561 0.59805198,0.35008397 0.53395394,0.32022062 0.53428334,0.31826758 0.5000002,0.31625324 0.5000002,0.3142457 0.46604675,0.32022041 0.46571736,0.31826737 0.433031,0.33179222 0.43237393,0.32999328 0.40194845,0.35008356 0.40096923,0.3485152 0.37389536,0.37389494 0.37260753,0.37260711 0.3500838,0.40194805 0.34851544,0.40096882 0.33179242,0.43303078
        ///0.32999348,0.43 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextureCoordinates {
            get {
                return ResourceManager.GetString("TextureCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 2 0 2 3 4 5 6 4 6 7 8 9 5 8 5 4 8 10 11 8 11 9 12 13 11 12 11 10 14 15 13 14 13 12 16 17 15 16 15 14 16 18 19 16 19 17 20 21 19 20 19 18 20 22 23 20 23 21 24 25 23 24 23 22 26 27 25 26 25 24 28 29 27 28 27 26 28 30 31 28 31 29 32 33 31 32 31 30 32 34 35 32 35 33 36 37 35 36 35 34 36 38 39 36 39 37 40 41 39 40 39 38 40 42 43 40 43 41 44 45 43 44 43 42 46 47 45 46 45 44 48 49 47 48 47 46 48 50 51 48 51 49 50 52 53 50 53 51 54 55 53 54 53 52 54 56 57 54 57 55 58 59 57 58 57 56 58 60 61 58 61 59 62 63 61 62 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriangleIndices {
            get {
                return ResourceManager.GetString("TriangleIndices", resourceCulture);
            }
        }
    }
}
