//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Views._3D {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pawn_Mesh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pawn_Mesh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Views._3D.Pawn_Mesh", typeof(Pawn_Mesh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.47724345,0.47330137,0.74042184 0.70710678,0.70710678,0 0.55557069,0.8314693,0 0.38850731,0.58144113,0.71483444 0.019395506,0.046824643,-0.99871481 0.38268519,0.92387881,0 0.55557069,0.8314693,0 0.028157818,0.042141103,-0.99871481 0.0098877772,0.049708824,-0.99871481 0.19509179,0.98078499,0 1.4599161E-07,0.050682667,-0.99871481 2.8805037E-06,1,0 -0.0098876334,0.049708835,-0.99871481
        ///-0.19508902,0.98078554,0 -0.019395301,0.046824718,-0.99871481 -0.3826812,0.92388046,0 -0.028157734,0.042141122,-0.99871481 - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Normals {
            get {
                return ResourceManager.GetString("Normals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.5999999,-4.4000001,0.172243 7.5999999,-4.4000001,0.086121 7.4714179,-4.294476,0.086121 7.4714179,-4.294476,0.172243 7.324719,-4.216063,0 7.324719,-4.216063,0.043060999 7.4714179,-4.294476,0.043060999 7.4714179,-4.294476,0 7.1655412,-4.1677771,0 7.1655412,-4.1677771,0.043060999 7.000001,-4.1514721,0 7.000001,-4.1514721,0.043060999 6.8344622,-4.1677761,0
        ///6.8344622,-4.1677761,0.043060999 6.675283,-4.2160621,0 6.675283,-4.2160621,0.043060999 6.528584,-4.2944741,0 6.528584,-4.2944741,0.043060999 6.400001,-4.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.64424165,0.35575835 0.63689182,0.36310818 0.60623165,0.33690556 0.61177417,0.32786778 0.56901213,0.32618259 0.5706976,0.32151432 0.60361525,0.34114059 0.60109799,0.34519736 0.53497764,0.31412631 0.5358215,0.30904584 0.5000002,0.30998738 0.50000021,0.30476041 0.46502307,0.31412609 0.46417923,0.30904561 0.43098828,0.32618237 0.42930282,0.32151408 0.39890246,0.34519693 0.3963852,0.34114016 0.36988635,0.36988591 0.36656625,0.3665658 0.34519718,0.39890204 0.34114041,0.39638478 0.32618256,0.43098807
        ///0.32151429 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextureCoordinates {
            get {
                return ResourceManager.GetString("TextureCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 2 0 2 3 4 5 6 4 6 7 8 9 5 8 5 4 8 10 11 8 11 9 12 13 11 12 11 10 14 15 13 14 13 12 16 17 15 16 15 14 16 18 19 16 19 17 20 21 19 20 19 18 20 22 23 20 23 21 24 25 23 24 23 22 26 27 25 26 25 24 28 29 27 28 27 26 28 30 31 28 31 29 32 33 31 32 31 30 32 34 35 32 35 33 36 37 35 36 35 34 36 38 39 36 39 37 40 41 39 40 39 38 40 42 43 40 43 41 44 45 43 44 43 42 46 47 45 46 45 44 48 49 47 48 47 46 48 50 51 48 51 49 50 52 53 50 53 51 54 55 53 54 53 52 54 56 57 54 57 55 58 59 57 58 57 56 58 60 61 58 61 59 62 63 61 62 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriangleIndices {
            get {
                return ResourceManager.GetString("TriangleIndices", resourceCulture);
            }
        }
    }
}
