//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Views._3D {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queen_Mesh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queen_Mesh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Views._3D.Queen_Mesh", typeof(Queen_Mesh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.70710683,0.70710674,0 0.70710681,0.70710672,0.00021289777 0.010813713,0.016183847,-0.99981056 0.55557065,0.83146933,0 0.0074486342,0.017982515,-0.99981056 0.38268487,0.92387894,0 0.19509179,0.98078499,7.4071991E-05 0.19509179,0.98078499,0 2.8805042E-06,0.99999999,0.00016325146 2.8805043E-06,1,0 -0.003797241,0.019090156,-0.99981056 -0.19508898,0.98078555,0 -0.0074485641,0.01798254,-0.99981056
        ///-0.38268133,0.9238804,0 -0.55556936,0.83147019,3.2653323E-05 -0.55556936,0.83147019,0 -0.70710516,0.7071084,-0.000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Normals {
            get {
                return ResourceManager.GetString("Normals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.40000001,-6.4000001,0.016519001 -0.40000001,-6.4000001,0 -0.52858198,-6.294476,0 -0.52858198,-6.294476,0.016519001 -0.67528099,-6.216063,0 -0.67528099,-6.216063,0.016519001 -0.83445901,-6.1677771,0 -0.83445901,-6.1677771,0.016519001 -0.99999899,-6.1514721,0 -0.99999899,-6.1514721,0.016519001 -1.165538,-6.1677761,0 -1.165538,-6.1677761,0.016519001 -1.324717,-6.2160621,0
        ///-1.324717,-6.2160621,0.016519001 -1.471416,-6.2944741,0 -1.471416,-6.2944741,0.016519001 -1.599999,-6.3999991,0 -1.599999,-6.3999991,0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.63133293,0.3686671 0.63007582,0.3699242 0.60106912,0.34524382 0.60202284,0.34370891 0.56899279,0.32623599 0.56963166,0.32447098 0.53496791,0.31418438 0.53528786,0.31226454 0.50000022,0.31004711 0.50000022,0.30807231 0.46503274,0.31418417 0.4647128,0.31226433 0.43100765,0.32623577 0.43036878,0.32447075 0.39893135,0.34524339 0.39797764,0.34370848 0.36992442,0.36992398 0.36866732,0.36866687 0.34524362,0.39893094 0.34370871,0.39797722 0.32623597,0.43100742 0.32447095,0.43036855 0.3141842,0.46503207
        ///0.3122643 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextureCoordinates {
            get {
                return ResourceManager.GetString("TextureCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 2 0 2 3 4 5 3 4 3 2 6 7 5 6 5 4 6 8 9 6 9 7 10 11 9 10 9 8 12 13 11 12 11 10 14 15 13 14 13 12 14 16 17 14 17 15 18 19 17 18 17 16 18 20 21 18 21 19 22 23 21 22 21 20 24 25 23 24 23 22 26 27 25 26 25 24 26 28 29 26 29 27 30 31 29 30 29 28 30 32 33 30 33 31 34 35 33 34 33 32 34 36 37 34 37 35 38 39 37 38 37 36 38 40 41 38 41 39 42 43 41 42 41 40 44 45 43 44 43 42 46 47 45 46 45 44 46 48 49 46 49 47 48 50 51 48 51 49 52 53 51 52 51 50 52 54 55 52 55 53 56 57 55 56 55 54 56 58 59 56 59 57 60 61 59 60 59 58 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriangleIndices {
            get {
                return ResourceManager.GetString("TriangleIndices", resourceCulture);
            }
        }
    }
}
