//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Views._3D {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rook_Mesh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rook_Mesh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Views._3D.Rook_Mesh", typeof(Rook_Mesh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.24883428,0.24446995,0.93718512 0.70710678,0.70710678,0 0.55557069,0.8314693,0 0.20258139,0.30318456,0.93114978 0.013851919,0.03344131,-0.99934469 0.38268519,0.92387881,0 0.55557069,0.8314693,0 0.020109803,0.030096411,-0.99934469 0.007061671,0.03550114,-0.99934469 0.19509179,0.98078499,0 1.0426456E-07,0.036196641,-0.99934469 2.8805037E-06,1,0 -0.0070615684,0.035501148,-0.99934469
        ///-0.19508902,0.98078554,0 -0.013851772,0.033441364,-0.99934469 -0.3826812,0.92388046,0 -0.020109742,0.030096424,-0.99934469 -0.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Normals {
            get {
                return ResourceManager.GetString("Normals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.5999999,-6.4000001,0.123118 7.5999999,-6.4000001,0.101007 7.4714179,-6.294476,0.101007 7.4714179,-6.294476,0.123118 7.324719,-6.216063,0 7.324719,-6.216063,0.030734001 7.4714179,-6.294476,0.030734001 7.4714179,-6.294476,0 7.1655412,-6.1677771,0 7.1655412,-6.1677771,0.030734001 7.000001,-6.1514721,0 7.000001,-6.1514721,0.030734001 6.8344622,-6.1677761,0
        ///6.8344622,-6.1677761,0.030734001 6.675283,-6.2160621,0 6.675283,-6.2160621,0.030734001 6.528584,-6.2944741,0 6.528584,-6.2944741,0.030734001 6.400001,-6.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.63990402,0.36009598 0.6380489,0.3619511 0.60710593,0.33548605 0.6085063,0.33320768 0.56897916,0.32627354 0.57017481,0.32296625 0.60283407,0.34240137 0.60104878,0.34527648 0.53496113,0.31422521 0.53555983,0.31062689 0.5000002,0.3100891 0.5000002,0.30638741 0.46503958,0.31422499 0.46444089,0.31062667 0.43102125,0.32627332 0.42982561,0.32296602 0.39895166,0.34527606 0.39716639,0.34240094 0.36995118,0.36995074 0.36759728,0.36759683 0.3452763,0.39895125 0.34240119,0.39716597 0.32627351,0.43102103
        ///0.32296622,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextureCoordinates {
            get {
                return ResourceManager.GetString("TextureCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 2 0 2 3 4 5 6 4 6 7 8 9 5 8 5 4 8 10 11 8 11 9 12 13 11 12 11 10 14 15 13 14 13 12 16 17 15 16 15 14 16 18 19 16 19 17 20 21 19 20 19 18 20 22 23 20 23 21 24 25 23 24 23 22 26 27 25 26 25 24 28 29 27 28 27 26 28 30 31 28 31 29 32 33 31 32 31 30 32 34 35 32 35 33 36 37 35 36 35 34 36 38 39 36 39 37 40 41 39 40 39 38 40 42 43 40 43 41 44 45 43 44 43 42 46 47 45 46 45 44 48 49 47 48 47 46 48 50 51 48 51 49 50 52 53 50 53 51 54 55 53 54 53 52 54 56 57 54 57 55 58 59 57 58 57 56 58 60 61 58 61 59 62 63 61 62 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriangleIndices {
            get {
                return ResourceManager.GetString("TriangleIndices", resourceCulture);
            }
        }
    }
}
